## Análise de Processos com Navios Tanque (Sprint 3)

### Aqui usaremos o pm4py para percorrer planilhas do excel com os dados de processos de Navio tanque.

In [37]:
import pandas as pd
import pm4py

In [38]:
# lendo arquivo .csv já convertido
naviosTanque = pd.read_csv("C:\\Users\\betsabenogueira\\Documents\\Relatório_NT_2022.csv")
naviosTanque

,Unidade Operativa,Instalação Naval,Navio,Volume Programado,Data Prevista de Chegada,Data Prevista de Saída,Viagem,Destino,H.O.C.,Amarração,...,Densidade 20°,Volume de Água Livre (m³),Responsável,Classe do Navio,Rebocador,Hora Top,Alívio Crítico,Apuração Alívio Crítico,Volume Acumulado Perdas,Lifter
0,UN-BS,PETROBRAS 67,FORTALEZA KNUTSEN,80000,27/04/2022 12:00:00,28/04/2022 09:30:00,423 TA,T.B.N.,27/04/2022 03:00:00,27/04/2022 09:04:00,...,"0,8757",Valor Medido,BSJ9,Classe DP2,NAO SOLICITADO,28/04/2022 12:43:00,48h,NaN,0,NaN
1,BUZIOS,PETROBRAS 77,EAGLE PAULINIA,80000,25/07/2022 12:00:00,26/07/2022 12:30:00,102 TA,T.B.N.,25/07/2022 12:00:00,25/07/2022 15:12:00,...,"0,8795","36,56",DAGD,Classe DP2,NAO SOLICITADO,26/07/2022 21:32:14,48h,NaN,0,NaN
2,UN-BS,FPSO Cidade de Saquarema,DAN SABIA,60000,11/05/2022 12:00:00,12/05/2022 11:00:00,315 TA,T.B.N.,11/05/2022 08:30:00,11/05/2022 15:40:00,...,"0,8677",NaN,TVFE,Classe DP2,MAERSK TRAVELLER,14/05/2022 23:27:00,OK,NaN,0,NaN
3,UN-ES,FSO Cidade de Macaé - MV15,TOVE KNUTSEN,80000,11/05/2022 14:00:00,12/05/2022 16:00:00,-,CARGA EQUINOR,11/05/2022 06:00:00,11/05/2022 15:00:00,...,"0,9072",AD,F8C9,Convencional,NAO SOLICITADO,18/07/2022 13:02:04,OK,NaN,0,NaN
4,UN-ES,FSO Cidade de Macaé - MV15,TOVE KNUTSEN,80000,11/05/2022 14:00:00,12/05/2022 16:00:00,-,CARGA EQUINOR,11/05/2022 06:00:00,11/05/2022 15:00:00,...,"0,9072",AD,F8C9,Convencional,NAO SOLICITADO,18/07/2022 13:02:04,OK,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2093,BUZIOS,PETROBRAS 75,RIO 2016,88000,30/12/2022 12:00:00,01/01/2023 04:30:00,109 TA,FPSO P-68 BERBIGAO,30/12/2022 23:42:00,31/12/2022 02:42:00,...,"0,8771",NaN,XDNY,Convencional,Não Socilitado,01/01/2023 02:50:05,48h,NaN,0,NaN
2094,UN-BS,FPSO CARIOCA MV30,BRASIL 2014,155000,30/12/2022 13:57:45,01/01/2023 11:44:00,366 TA,T.B.N.,31/12/2022 00:01:00,31/12/2022 04:00:00,...,"0,8854",NaN,C1HV,Convencional,Não Socilitado,02/01/2023 18:55:17,OK,NaN,0,NaN
2095,BUZIOS,PETROBRAS 77,EAGLE PAULINIA,80000,01/01/2023 12:00:00,01/01/2023 12:55:00,122 TA,T.B.N.,31/12/2022 08:00:00,31/12/2022 13:00:00,...,"0,8785",NaN,XDNY,Convencional,Não Socilitado,01/01/2023 09:58:49,48h,NaN,0,NaN
2096,UN-BC,PETROBRAS 48,RECIFE KNUTSEN,50000,31/12/2022 13:00:00,01/01/2023 19:40:00,457 TA,ILHA DAGUA,31/12/2022 17:21:00,31/12/2022 19:36:00,...,"0,9141",Valor Medido,NXB6,Classe DP2,NaN,01/01/2023 23:10:00,48h,NaN,0,NaN
2097,UN-BS,PETROBRAS 69,EAGLE PARANA,90000,31/12/2022 19:00:00,01/01/2023 22:00:00,414 TA,T.B.N.,31/12/2022 20:30:00,01/01/2023 00:00:00,...,"0,8727",NaN,TVX3,Convencional,Não Socilitado,05/01/2023 06:20:00,OK,NaN,0,NaN

In [39]:
# convertendo arquivo excel para .csv
excel_file = "C:\\Users\\betsabenogueira\\Downloads\\Relatório_NT_2022.xlsx"
df = pd.read_excel(excel_file)

csv_file = "betsabe pasta\\Relatório_NT_2022-convertido.csv"  # Nome do arquivo CSV de saída
df.to_csv(csv_file, index=False)
csv_file

'betsabe pasta\\Relatório_NT_2022-convertido.csv'

In [40]:
pd.read_csv(csv_file)
# cada linha agora é um caso, diferente de antes.

,Unidade Operativa,Instalação Naval,Navio,Volume Programado,Data Prevista de Chegada,Data Prevista de Saída,Viagem,Destino,H.O.C.,Amarração,...,Densidade 20°,Volume de Água Livre (m³),Responsável,Classe do Navio,Rebocador,Hora Top,Alívio Crítico,Apuração Alívio Crítico,Volume Acumulado Perdas,Lifter
0,UN-BS,PETROBRAS 67,FORTALEZA KNUTSEN,80000,27/04/2022 12:00:00,28/04/2022 09:30:00,423 TA,T.B.N.,27/04/2022 03:00:00,27/04/2022 09:04:00,...,"0,8757",Valor Medido,BSJ9,Classe DP2,NAO SOLICITADO,28/04/2022 12:43:00,48h,NaN,0,NaN
1,BUZIOS,PETROBRAS 77,EAGLE PAULINIA,80000,25/07/2022 12:00:00,26/07/2022 12:30:00,102 TA,T.B.N.,25/07/2022 12:00:00,25/07/2022 15:12:00,...,"0,8795","36,56",DAGD,Classe DP2,NAO SOLICITADO,26/07/2022 21:32:14,48h,NaN,0,NaN
2,UN-BS,FPSO Cidade de Saquarema,DAN SABIA,60000,11/05/2022 12:00:00,12/05/2022 11:00:00,315 TA,T.B.N.,11/05/2022 08:30:00,11/05/2022 15:40:00,...,"0,8677",NaN,TVFE,Classe DP2,MAERSK TRAVELLER,14/05/2022 23:27:00,OK,NaN,0,NaN
3,UN-ES,FSO Cidade de Macaé - MV15,TOVE KNUTSEN,80000,11/05/2022 14:00:00,12/05/2022 16:00:00,-,CARGA EQUINOR,11/05/2022 06:00:00,11/05/2022 15:00:00,...,"0,9072",AD,F8C9,Convencional,NAO SOLICITADO,18/07/2022 13:02:04,OK,NaN,0,NaN
4,UN-ES,FSO Cidade de Macaé - MV15,TOVE KNUTSEN,80000,11/05/2022 14:00:00,12/05/2022 16:00:00,-,CARGA EQUINOR,11/05/2022 06:00:00,11/05/2022 15:00:00,...,"0,9072",AD,F8C9,Convencional,NAO SOLICITADO,18/07/2022 13:02:04,OK,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2093,BUZIOS,PETROBRAS 75,RIO 2016,88000,30/12/2022 12:00:00,01/01/2023 04:30:00,109 TA,FPSO P-68 BERBIGAO,30/12/2022 23:42:00,31/12/2022 02:42:00,...,"0,8771",NaN,XDNY,Convencional,Não Socilitado,01/01/2023 02:50:05,48h,NaN,0,NaN
2094,UN-BS,FPSO CARIOCA MV30,BRASIL 2014,155000,30/12/2022 13:57:45,01/01/2023 11:44:00,366 TA,T.B.N.,31/12/2022 00:01:00,31/12/2022 04:00:00,...,"0,8854",NaN,C1HV,Convencional,Não Socilitado,02/01/2023 18:55:17,OK,NaN,0,NaN
2095,BUZIOS,PETROBRAS 77,EAGLE PAULINIA,80000,01/01/2023 12:00:00,01/01/2023 12:55:00,122 TA,T.B.N.,31/12/2022 08:00:00,31/12/2022 13:00:00,...,"0,8785",NaN,XDNY,Convencional,Não Socilitado,01/01/2023 09:58:49,48h,NaN,0,NaN
2096,UN-BC,PETROBRAS 48,RECIFE KNUTSEN,50000,31/12/2022 13:00:00,01/01/2023 19:40:00,457 TA,ILHA DAGUA,31/12/2022 17:21:00,31/12/2022 19:36:00,...,"0,9141",Valor Medido,NXB6,Classe DP2,NaN,01/01/2023 23:10:00,48h,NaN,0,NaN
2097,UN-BS,PETROBRAS 69,EAGLE PARANA,90000,31/12/2022 19:00:00,01/01/2023 22:00:00,414 TA,T.B.N.,31/12/2022 20:30:00,01/01/2023 00:00:00,...,"0,8727",NaN,TVX3,Convencional,Não Socilitado,05/01/2023 06:20:00,OK,NaN,0,NaN

### TRATAMENTO DOS DADOS NAVIO TANQUE

In [41]:
# - Bases: ‘Relatório_NT_2023.xlsx’ e Relatório_NT_2022.xlsx’
# - Concatenar as duas bases

navioTanque1 = pd.read_excel("C:\\Users\\betsabenogueira\\Downloads\\Relatório_NT_2022.xlsx")
navioTanque2 = pd.read_excel("C:\\Users\\betsabenogueira\\Downloads\\Relatório_NT_2023.xlsx")

# Concatena os DataFrames
df_concatenado = pd.concat([navioTanque1, navioTanque2], ignore_index=True)

# Escreve o DataFrame concatenado em um novo arquivo Excel
df_concatenado.to_excel("betsabe pasta\\navios_concatenado.xlsx", index=False)
df_concatenado

,Unidade Operativa,Instalação Naval,Navio,Volume Programado,Data Prevista de Chegada,Data Prevista de Saída,Viagem,Destino,H.O.C.,Amarração,...,Densidade 20°,Volume de Água Livre (m³),Responsável,Classe do Navio,Rebocador,Hora Top,Alívio Crítico,Apuração Alívio Crítico,Volume Acumulado Perdas,Lifter
0,UN-BS,PETROBRAS 67,FORTALEZA KNUTSEN,80000,27/04/2022 12:00:00,28/04/2022 09:30:00,423 TA,T.B.N.,27/04/2022 03:00:00,27/04/2022 09:04:00,...,"0,8757",Valor Medido,BSJ9,Classe DP2,NAO SOLICITADO,28/04/2022 12:43:00,48h,NaN,0,NaN
1,BUZIOS,PETROBRAS 77,EAGLE PAULINIA,80000,25/07/2022 12:00:00,26/07/2022 12:30:00,102 TA,T.B.N.,25/07/2022 12:00:00,25/07/2022 15:12:00,...,"0,8795","36,56",DAGD,Classe DP2,NAO SOLICITADO,26/07/2022 21:32:14,48h,NaN,0,NaN
2,UN-BS,FPSO Cidade de Saquarema,DAN SABIA,60000,11/05/2022 12:00:00,12/05/2022 11:00:00,315 TA,T.B.N.,11/05/2022 08:30:00,11/05/2022 15:40:00,...,"0,8677",NaN,TVFE,Classe DP2,MAERSK TRAVELLER,14/05/2022 23:27:00,OK,NaN,0,NaN
3,UN-ES,FSO Cidade de Macaé - MV15,TOVE KNUTSEN,80000,11/05/2022 14:00:00,12/05/2022 16:00:00,-,CARGA EQUINOR,11/05/2022 06:00:00,11/05/2022 15:00:00,...,"0,9072",AD,F8C9,Convencional,NAO SOLICITADO,18/07/2022 13:02:04,OK,NaN,0,NaN
4,UN-ES,FSO Cidade de Macaé - MV15,TOVE KNUTSEN,80000,11/05/2022 14:00:00,12/05/2022 16:00:00,-,CARGA EQUINOR,11/05/2022 06:00:00,11/05/2022 15:00:00,...,"0,9072",AD,F8C9,Convencional,NAO SOLICITADO,18/07/2022 13:02:04,OK,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3280,UN-BS,PETROBRAS 66,NT LISBOA,76000,31/07/2023 00:00:00,01/08/2023 04:06:00,PG043,CARGA PETROGAL,30/07/2023 00:01:00,31/07/2023 01:00:00,...,"0,8715",NaN,TVX3,Classe DP2,NaN,02/08/2023 02:57:57,OK,NaN,0,NaN
3281,UN-ES,FSO Cidade de Macaé - MV15,EAGLE CAMBE,151000,31/07/2023 03:01:00,01/08/2023 15:23:45,055 TA,T.B.N.,30/07/2023 20:00:00,30/07/2023 23:32:00,...,"0,8815",Valor Medido,TES1,Convencional,NaN,01/08/2023 21:08:55,OK,NaN,0,NaN
3282,UN-ES,PETROBRAS 58,ANGRA DOS REIS,70000,31/07/2023 08:00:00,01/08/2023 16:00:00,429 TA,T.B.N.,31/07/2023 14:00:00,31/07/2023 19:20:00,...,"0,889","74,5",CSC4,Convencional,NaN,04/08/2023 20:09:04,OK,NaN,0,NaN
3283,UN-BS,FPSO Cidade de Maricá,EAGLE PAULINIA,155000,31/07/2023 08:00:00,01/08/2023 16:55:00,155 TA,T.B.N.,31/07/2023 09:00:00,31/07/2023 12:25:00,...,"0,8711",NaN,TVX3,Convencional,NaN,02/08/2023 15:27:49,OK,NaN,0,NaN
3284,UN-BUZ,PETROBRAS 76,ELKA LEBLON,80000,31/07/2023 13:00:00,01/08/2023 18:00:00,402 TA,T.B.N.,31/07/2023 11:30:00,31/07/2023 15:13:00,...,"0,8762",NaN,ZPDI,Convencional,REED BUCK,02/08/2023 13:09:23,OK,NaN,0,NaN

In [49]:
# - Retirar acentos e ç para facilitar análises futuras
import pandas as pd
from unidecode import unidecode

# Remover acentos e substituir caracteres especiais
naviosTanque_1_2 = pd.read_excel("betsabe pasta\\navios_concatenado.xlsx")
df_concatenado_sem_acento = naviosTanque_1_2.map(lambda x: unidecode(str(x)) if isinstance(x, str) else x)
df_concatenado_sem_acento

,Unidade Operativa,Instalação Naval,Navio,Volume Programado,Data Prevista de Chegada,Data Prevista de Saída,Viagem,Destino,H.O.C.,Amarração,...,Densidade 20°,Volume de Água Livre (m³),Responsável,Classe do Navio,Rebocador,Hora Top,Alívio Crítico,Apuração Alívio Crítico,Volume Acumulado Perdas,Lifter
0,UN-BS,PETROBRAS 67,FORTALEZA KNUTSEN,80000,27/04/2022 12:00:00,28/04/2022 09:30:00,423 TA,T.B.N.,27/04/2022 03:00:00,27/04/2022 09:04:00,...,"0,8757",Valor Medido,BSJ9,Classe DP2,NAO SOLICITADO,28/04/2022 12:43:00,48h,NaN,0,NaN
1,BUZIOS,PETROBRAS 77,EAGLE PAULINIA,80000,25/07/2022 12:00:00,26/07/2022 12:30:00,102 TA,T.B.N.,25/07/2022 12:00:00,25/07/2022 15:12:00,...,"0,8795","36,56",DAGD,Classe DP2,NAO SOLICITADO,26/07/2022 21:32:14,48h,NaN,0,NaN
2,UN-BS,FPSO Cidade de Saquarema,DAN SABIA,60000,11/05/2022 12:00:00,12/05/2022 11:00:00,315 TA,T.B.N.,11/05/2022 08:30:00,11/05/2022 15:40:00,...,"0,8677",NaN,TVFE,Classe DP2,MAERSK TRAVELLER,14/05/2022 23:27:00,OK,NaN,0,NaN
3,UN-ES,FSO Cidade de Macae - MV15,TOVE KNUTSEN,80000,11/05/2022 14:00:00,12/05/2022 16:00:00,-,CARGA EQUINOR,11/05/2022 06:00:00,11/05/2022 15:00:00,...,"0,9072",AD,F8C9,Convencional,NAO SOLICITADO,18/07/2022 13:02:04,OK,NaN,0,NaN
4,UN-ES,FSO Cidade de Macae - MV15,TOVE KNUTSEN,80000,11/05/2022 14:00:00,12/05/2022 16:00:00,-,CARGA EQUINOR,11/05/2022 06:00:00,11/05/2022 15:00:00,...,"0,9072",AD,F8C9,Convencional,NAO SOLICITADO,18/07/2022 13:02:04,OK,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3280,UN-BS,PETROBRAS 66,NT LISBOA,76000,31/07/2023 00:00:00,01/08/2023 04:06:00,PG043,CARGA PETROGAL,30/07/2023 00:01:00,31/07/2023 01:00:00,...,"0,8715",NaN,TVX3,Classe DP2,NaN,02/08/2023 02:57:57,OK,NaN,0,NaN
3281,UN-ES,FSO Cidade de Macae - MV15,EAGLE CAMBE,151000,31/07/2023 03:01:00,01/08/2023 15:23:45,055 TA,T.B.N.,30/07/2023 20:00:00,30/07/2023 23:32:00,...,"0,8815",Valor Medido,TES1,Convencional,NaN,01/08/2023 21:08:55,OK,NaN,0,NaN
3282,UN-ES,PETROBRAS 58,ANGRA DOS REIS,70000,31/07/2023 08:00:00,01/08/2023 16:00:00,429 TA,T.B.N.,31/07/2023 14:00:00,31/07/2023 19:20:00,...,"0,889","74,5",CSC4,Convencional,NaN,04/08/2023 20:09:04,OK,NaN,0,NaN
3283,UN-BS,FPSO Cidade de Marica,EAGLE PAULINIA,155000,31/07/2023 08:00:00,01/08/2023 16:55:00,155 TA,T.B.N.,31/07/2023 09:00:00,31/07/2023 12:25:00,...,"0,8711",NaN,TVX3,Convencional,NaN,02/08/2023 15:27:49,OK,NaN,0,NaN
3284,UN-BUZ,PETROBRAS 76,ELKA LEBLON,80000,31/07/2023 13:00:00,01/08/2023 18:00:00,402 TA,T.B.N.,31/07/2023 11:30:00,31/07/2023 15:13:00,...,"0,8762",NaN,ZPDI,Convencional,REED BUCK,02/08/2023 13:09:23,OK,NaN,0,NaN

In [43]:
'''
- Padronizar o formato de data e hora - Colunas: “Data Prevista de Chegada”, “Data Prevista de Saída”, “H.O.C.”,
“Amarração”,” Início de Bombeio”, “Fim de Bombeio”,” Desamarração”, “H.O.S.”,” Início Primeira Amarração”,” Fim Primeira Amarração”,
"Início Primeira Conexão”,” Fim Primeira Conexão”,” Início Primeiro Bombeio”,” Fim Último Bombeio”,” Início Última Desconexão”,
” Fim Última Desconexão”,” Início Última Desamarração”,” Fim Última Desamarração”
'''

'\n- Padronizar o formato de data e hora - Colunas: “Data Prevista de Chegada”, “Data Prevista de Saída”, “H.O.C.”,\n“Amarração”,” Início de Bombeio”, “Fim de Bombeio”,” Desamarração”, “H.O.S.”,” Início Primeira Amarração”,” Fim Primeira Amarração”,\n"Início Primeira Conexão”,” Fim Primeira Conexão”,” Início Primeiro Bombeio”,” Fim Último Bombeio”,” Início Última Desconexão”,\n” Fim Última Desconexão”,” Início Última Desamarração”,” Fim Última Desamarração”\n'

In [44]:
''' 
- Remover as colunas que não são importantes no momento (“Classe do Navio”, “Rebocador”, “Hora Top”, “Alívio Crítico”, 
  “Apuração Alívio Crítico”, “Volume Acumulado Perdas”, “Lifter”) 
'''
naviosTanque_1_2_sem_colunas = naviosTanque_1_2.drop(columns=["Classe do Navio","Rebocador","Hora Top","Alívio Crítico","Apuração Alívio Crítico","Volume Acumulado Perdas","Lifter"])
naviosTanque_1_2_sem_colunas

,Unidade Operativa,Instalação Naval,Navio,Volume Programado,Data Prevista de Chegada,Data Prevista de Saída,Viagem,Destino,H.O.C.,Amarração,...,Volume Retirado,Estaçao,Bsw (%),H2SOleo (mg/kg),H2SAgua (mg/l),Salinidade (mg/l),Temperatura (°C),Densidade 20°,Volume de Água Livre (m³),Responsável
0,UN-BS,PETROBRAS 67,FORTALEZA KNUTSEN,80000,27/04/2022 12:00:00,28/04/2022 09:30:00,423 TA,T.B.N.,27/04/2022 03:00:00,27/04/2022 09:04:00,...,81382.81,Proa,"0,2","0,2","0,5",102,"43,8","0,8757",Valor Medido,BSJ9
1,BUZIOS,PETROBRAS 77,EAGLE PAULINIA,80000,25/07/2022 12:00:00,26/07/2022 12:30:00,102 TA,T.B.N.,25/07/2022 12:00:00,25/07/2022 15:12:00,...,81704.09,Proa,"0,2","0,35",AD,32,"44,96","0,8795","36,56",DAGD
2,UN-BS,FPSO Cidade de Saquarema,DAN SABIA,60000,11/05/2022 12:00:00,12/05/2022 11:00:00,315 TA,T.B.N.,11/05/2022 08:30:00,11/05/2022 15:40:00,...,58883.00,Proa,"0,2",0,8,72,"48,92","0,8677",NaN,TVFE
3,UN-ES,FSO Cidade de Macaé - MV15,TOVE KNUTSEN,80000,11/05/2022 14:00:00,12/05/2022 16:00:00,-,CARGA EQUINOR,11/05/2022 06:00:00,11/05/2022 15:00:00,...,79486.66,Proa,"1,96",0,AD,1112,"24,2","0,9072",AD,F8C9
4,UN-ES,FSO Cidade de Macaé - MV15,TOVE KNUTSEN,80000,11/05/2022 14:00:00,12/05/2022 16:00:00,-,CARGA EQUINOR,11/05/2022 06:00:00,11/05/2022 15:00:00,...,79486.66,Proa,"1,96",0,AD,1112,"24,2","0,9072",AD,F8C9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3280,UN-BS,PETROBRAS 66,NT LISBOA,76000,31/07/2023 00:00:00,01/08/2023 04:06:00,PG043,CARGA PETROGAL,30/07/2023 00:01:00,31/07/2023 01:00:00,...,76781.44,Proa,"0,3","0,74","0,78",213,40,"0,8715",NaN,TVX3
3281,UN-ES,FSO Cidade de Macaé - MV15,EAGLE CAMBE,151000,31/07/2023 03:01:00,01/08/2023 15:23:45,055 TA,T.B.N.,30/07/2023 20:00:00,30/07/2023 23:32:00,...,154121.00,-,"0,3",Valor Medido,Valor Medido,262,"22,3","0,8815",Valor Medido,TES1
3282,UN-ES,PETROBRAS 58,ANGRA DOS REIS,70000,31/07/2023 08:00:00,01/08/2023 16:00:00,429 TA,T.B.N.,31/07/2023 14:00:00,31/07/2023 19:20:00,...,71039.00,Proa,"0,4","0,34",NaN,453,"39,5","0,889","74,5",CSC4
3283,UN-BS,FPSO Cidade de Maricá,EAGLE PAULINIA,155000,31/07/2023 08:00:00,01/08/2023 16:55:00,155 TA,T.B.N.,31/07/2023 09:00:00,31/07/2023 12:25:00,...,150823.66,Proa,"0,2",Valor Medido,Valor Medido,"25,7","50,23","0,8711",NaN,TVX3
3284,UN-BUZ,PETROBRAS 76,ELKA LEBLON,80000,31/07/2023 13:00:00,01/08/2023 18:00:00,402 TA,T.B.N.,31/07/2023 11:30:00,31/07/2023 15:13:00,...,81372.15,Popa,"0,2","0,64",NaN,42,"41,23","0,8762",NaN,ZPDI

In [45]:
# - Tirar duplicatas
naviosTanque_sem_duplicatas = naviosTanque_1_2.drop_duplicates() # removendo as duplicatas
naviosTanque_sem_duplicatas.to_excel("betsabe pasta\\navios_sem_duplicatas.xlsx", index=False) # gerando um arquivo excel sem as duplicatas

In [50]:
# - Criar da nova coluna “ID”, considerando cada linha como um ID:
naviosTanque_sem_duplicatas['ID'] = range(0, len(naviosTanque_sem_duplicatas))
naviosTanque_sem_duplicatas.to_excel("betsabe pasta\\navios_colunaID.xlsx", index=False)

In [46]:
# - Criar a coluna UEP na posição 2 que pega o valor da coluna “Instalação Naval” e troca tudo que tem PETROBRÁS POR P- para ficar padronizado e similar as bases dos outros tipos de recursos.
naviosTanque_sem_duplicatas['UEP'] = naviosTanque_sem_duplicatas["Instalação Naval"].replace()

In [47]:
# - Retirando o espaço antes e no final dos nomes nas colunas UEP e Navio (pois existiam espaços aleatórios que impediriam a comparação com as outras bases).
navios_SD = pd.read_excel("betsabe pasta\\navios_sem_duplicatas.xlsx")

navios_sem_espacos = navios_SD["Unidade Operativa"].apply(lambda x: x.strip() if isinstance(x, str) else x)
navios_SD["Navio"].str.strip()

0        UN-BS
1       BUZIOS
2        UN-BS
3        UN-ES
4        UN-BS
         ...
3231     UN-BS
3232     UN-ES
3233     UN-ES
3234     UN-BS
3235    UN-BUZ
Name: Unidade Operativa, Length: 3236, dtype: object